CC=ghc
CFLAGS=--make -Wall
SOURCEDIR=Challenges
EXECUTABLE=main
INPUT=in
OUTPUT=out
EXPECTED=exp

CHALLENGE_DIRS=$(shell find $(SOURCEDIR) -mindepth 1 -maxdepth 1)
CHALLENGE_BINARIES=$(patsubst %,%/$(EXECUTABLE),$(CHALLENGE_DIRS))
CHALLENGE_OBJECT_FILES=$(patsubst %,%.o,$(CHALLENGE_BINARIES))
CHALLENGE_INTERFACE_FILES=$(patsubst %,%.hi,$(CHALLENGE_BINARIES))
CHALLENGE_OUTPUT_FILES=$(patsubst %,%.$(OUTPUT),$(CHALLENGE_BINARIES))

all: $(CHALLENGE_BINARIES)

%/$(EXECUTABLE): %/$(EXECUTABLE).hs
	$(CC) $(CFLAGS) -o $@ $<

.PHONY: clean test
.DELETE_ON_ERROR: $(CHALLENGE_OUTPUT_FILES)

clean:
	rm -f $(CHALLENGE_BINARIES) $(CHALLENGE_INTERFACE_FILES) $(CHALLENGE_OBJECT_FILES) $(CHALLENGE_OUTPUT_FILES)

test: $(CHALLENGE_OUTPUT_FILES)

%.$(OUTPUT): % %.$(INPUT) %.$(EXPECTED)
	$< $<.$(INPUT) >$@
	diff $@ $<.$(EXPECTED)
